#!/bin/sh

echo "🔒 Precommit: Linting and testing code..."
# Debugging lines
echo "Node version: $(node -v)"
echo "NPM version: $(npm -v)"
echo "Current directory: $(pwd)"
echo "Environment NODE_ENV: $NODE_ENV"


npm run lint && npm test
